[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "GPT"
icon = ":books:"
is_section = true

[[pages]]
path = "Generic_ChatGPT.py"
name = "Generic_ChatGPT"
icon = "ğŸ¤–"

[[pages]]
path = "Color_labeling_products_with_GPT4.py"
name = "Color_labeling_products_with_GPT4"
icon = "ğŸš€"
